spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/core
    username: core
    password: core
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    addresses: localhost:5672
    username: guest
    password: guest
    virtual-host: /
  cloud:
    function:
      definition: testFunction; studentFunction
    stream:
      bindings:
        testFunction-in-0:
          destination: test.in
          group: core
        studentFunction-in-0:
          destination: student.in
          group: core
        testFunction-out-0:
          destination: test.out
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      password: artpass
      connect-timeout: 60000
